### ISSUE TITLE
Scrum update #1 May 25th

### ISSUE THREAD

**Issue by omarkhs** [QMuncaster/RxOn#1]
What did you work on this past iteration (2 weeks)?

What were any major issues/challenges you ran into?

What do you plan to work on for this coming iteration (2 weeks)?

**Comment by costewart** [comment]
**Scrum Update:**
(1) In the previous two weeks, we each brainstormed 5 project ideas, decided on our favourite 2 in lab and then narrowed down on our final decision: RxOn, an online pharmacy. From there, we discussed all the different elements our program will include, and completed the project progress proposal - individually, I was responsible for drawing the sketches of different pages we envision and I helped make some prototypes so when we start building we can easily reference a unified design.

(2) We are all planning to start Assignment 2 early so that we can solidify our understanding of react, redux and meteor, in order to feel confident with integrating this into our project. We will set up our repo with the base files, make sure everyone in the team understands and feels comfortable with pushing/pulling code and allocate pages for each team member to begin working on.

(3) We haven’t started coding yet, so we haven’t run into any problems.

**Comment by omarkhs** [comment]
1. Discussed with team members which project to work on and the scope.
2. Not really, we haven't started coding yet!
3. Setting up the project boilerplate code and dev environment. Start with setting up the front-end code base.

**Comment by mandy169** [comment]
1. First came up with a project topic and worked on the project requirements with detailed pages and prototype pages

2. Decided what technologies we need to use based on the required ones from the course.

3. Decide the basic technologies to use and set up the basic environment for the project.

**Comment by QMuncaster** [comment]
1. We each came up with project ideas and decided on one as a group. We then planned the application, including what basic functionality it has for its 2 main user types.

2. It was sometimes difficult to discern what functionality is a minimal requirement and what is a standard requirement. There was also lots of discussion on how to simplify our minimal product, for example with fewer prescription statuses.

3. We plan to setup Meteor, and assign sub-tasks so that we can get some of the basic components for critical pages finished.
