### ISSUE TITLE
Restructuring main.js

### ISSUE THREAD

**Issue by omarkhs** [QMuncaster/RxOn#26]
Main.js right now just runs account code.

**Comment by QMuncaster** [comment]
moved accounts code to its own file in 'imports/startup/server'. see commit:
e2fe905bec6d1e9f07a18814e497a9d0423a7658

**Comment by omarkhs** [comment]
@QMuncaster 

sounds good, I have a question..wouldn't it be easier that we have one server directory and within that single server directory we can have sub directories of collections, api, etc.. ?

**Comment by QMuncaster** [comment]
I followed this: 
https://guide.meteor.com/structure.html

I think this makes more sense because sometimes we have a client file and a server file that should be kept closer together. An example being the prescriptions collection (client) and the authenticated methods and publications (server). I think moving the server files to the root server folders makes it less clear that they go together with the client.

Also I think in general for meteor apps, where 'server/index.js' works as the main server entry point, its good to have all of its imports be in the 'imports' folder... but I'm not sure about that.

**Comment by omarkhs** [comment]
Ah I see, okie good point.
