### ISSUE TITLE
validation of prescriptions

### ISSUE THREAD

**Issue by QMuncaster** [QMuncaster/RxOn#32]
@QMuncaster: For todo you put regarding server-side validation of rxName, rxStrength, rxDose before inserting prescription into database (prescriptions.js).

I think strings would probably be easiest to work with because name, dose and strength all have words in them (none are purely numerical).

Second why do we need a server side validation, the client can only enter info through form which is string.

**Comment by QMuncaster** [comment]
@omarkhs 
I think in general we can't count on client-side validation.
So for example, we should also have a server-side check that none of the fields are empty before we insert it into the db.

> I think strings would probably be easiest to work with
Sounds good then, the only validation left to do server-side would be empty string checks then :)

**Comment by omarkhs** [comment]
@QMuncaster 
if all we are checking is wether a field is empty (so that we don't get an empty string) then client side should suffice.

However I see your point, yes we should put server side validation because we never know what client is throwing at us if there is a bug or something. Anyways it's just an if-statement/error handling on server side lol

**Comment by QMuncaster** [comment]
Yup, lets just do it anyways.
I think the main benefit of doing it is we will have a reason to make sure the client handles a failed server request appropriately, up till now we just assume that it always works.

**Comment by omarkhs** [comment]
Okay sounds good!
