### ISSUE TITLE
 Scrum update #5 July 20

### ISSUE THREAD

**Issue by QMuncaster** [QMuncaster/RxOn#45]
(1) what you’ve worked on in the previous two weeks
(2) what you’ll be working on in the next two weeks
(3) where you might have gotten stuck during the last two weeks.

**Comment by QMuncaster** [comment]
(1) what you’ve worked on in the previous two weeks
I setup the logout route, added user roles to accounts, made prescriptions publication/subscribe, and made our create/update/delete operations secure server-side methods.

(2) what you’ll be working on in the next two weeks
I'll fix up routing for the pharmacist side, look into logging out users after inactivity, and depending on whats left, maybe work on payment integration, image uploads, or the pharmacist view of patients.

(3) where you might have gotten stuck during the last two weeks.
Making the NavBar disappear immediately upon logout was tough, and might need to be re-fixed after the UI update.

**Comment by mandy169** [comment]
(1) what you’ve worked on in the previous two weeks
Made the edit prescription functionality work, which retrieve data from the data base and store the data back to the data base, checked the validation of arguments before prescription's insertion using check package, rendered the patient name of a prescription so as to be seen by the ADMIN and checked server-side validation of removing a prescription .

(2) what you’ll be working on in the next two weeks
Will make the user name linked to individual prescription clickable and redirect it to its medical history, which can be only seen by the user of ADMIN. Will take part in the the billing functionality and other functionalities if needed.

(3) where you might have gotten stuck during the last two weeks.
I was having problem with the validation because I just checked validation in the front end, which is not enough. It'd been noticed by my partner and I finally got it done.

**Comment by omarkhs** [comment]
1. Complete UI overhaul to use Material UI. Changed forms, all buttons, NavBar etc..
Integrated all current actions by users through new UI. 

Added a table of prescriptions for pharmacy side to manage the prescriptions. Table has filter, sort, search, download functionalities  

2. I really want to work on adding billing functionality and prescription image upload functionality.

3. There were couple of config issues that took a long time to work out. Getting comfortable with Material UI. It was a bit daunting at first
